<?php
	require_once("Core/Assert.cb.php");
	require_once("Core/Dispatcher.class.php");
	require_once("Core/Controller.class.php");
	require_once("Core/Routeur.class.php");
	require_once("Core/Form.class.php");
	require_once("Core/Mysqldb.class.php");
	require_once("Model/Select.class.php");
?>